name: Build and push tagged images to Production
on:
  push:
    tags:
      - 'v*'
jobs:
  build_push_image:
    runs_on: ubuntu_latest

    steps:
      - uses: actions/checkout@v2

      - name: Build and push production image
        uses: docker/build-push-action@v1.1.1
        with:
          username: ${{ secrets.ACR_LOGIN }}
          password: ${{ secrets.ACR_PASSWORD }}
          registry: ${{ secrets.ACR_NAME }}
          repository: contoso-website
          tag_with_ref: true
